from __future__ import annotations


CLI_COMMAND_NAMES = [
    "help",
    "version",
    "init",
    "init-plain",
    "init-basic",
    "init-basic-plain",
    "agent-sync",
    "hooks-upgrade",
    "clean",
    "clean-confirm",
    "accept",
    "backup",
    "backup-list",
    "backup-clean",
    "restore",
    "context",
    "next",
    "discuss",
    "discuss-link",
    "capture",
    "capture-transition",
    "capture-link",
    "capture-requirement",
    "capture-change",
    "add",
    "grill",
    "lessons",
    "material",
    "change-material",
    "design-summary",
    "design-artifact",
    "design-plan",
    "design-reference",
    "design-reference-confirm",
    "design",
    "design-accept",
    "draft",
    "facts",
    "start",
    "light-start",
    "tasks",
    "plan",
    "plan-add-task",
    "plan-amend-task",
    "plan-reorder",
    "plan-depends",
    "plan-close",
    "plan-priority",
    "change-plan",
    "regression",
    "docs",
    "task",
    "task-read-confirm",
    "task-run-check",
    "task-evidence",
    "task-done",
    "task-restore",
    "task-pause",
    "fix",
    "audit",
    "change-migrate",
    "change-create",
    "change-package",
    "change-protect",
    "review",
    "change",
    "change-capture",
    "change-accept",
    "finish",
    "handoff",
    "status",
    "doctor",
    "doctor-install",
    "doctor-repair",
    "doctor-deep",
    "export",
    "export-requirement",
]

SKILL_COMMAND_NAMES = [
    name
    for name in CLI_COMMAND_NAMES
    if name
    not in {
        "help",
        "facts",
        "task-read-confirm",
        # 这些确定性子步骤由上层阶段技能调用，当前没有独立公开技能目录。
        "capture-transition",
        "design-summary",
        "design-artifact",
        "design-plan",
        "design-reference",
        "design-reference-confirm",
        "task-run-check",
        "task-evidence",
        "change-migrate",
        # 创建工作区是正式 CLI 内部入口，规划和变更技能会统一调用它，
        # 不为这个确定性子步骤额外生成一份公开技能。
        "change-create",
        "change-package",
        "change-protect",
        "change-material",
        # 通用审核由需求、设计和任务阶段技能调用，不额外暴露一份阶段外入口。
        "review",
    }
]

EXTRA_SDLC_SKILL_NAMES = [
    "sdlc-goal",
]
